psitsregistration/urls.py
from django.conf.urls import patterns, include, url
from psitsregistration.views import *
from profiles.views import *
from auth.views import *
from registration.views import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r"^$", attend, name='home'),
    url(r'^create_account/$', create_account, name='create_account'),
    url(r'^add_student/$', add_student, name='add_student'),
    url(r'^event/$', event, name='event'),
    url(r'^event/create/$', create_event, name='create_event'),
    url(r'^event/activate/$', activate_event, name='activate_event'),
    url(r'^event/deactivate/$', deactivate_event, name='deactivate_event'),
    url(r'^attend/$', attend , name='attend'),
    url(r'^attend/search/$', ajax_search_lastname , name='ajax_search_lastname'),
    url(r'^attend/barcode/$', register_barcode , name='register_barcode'),
    url(r'^attend/register/$', register , name='register'),
    url(r'^attend/withdraw/$', withdraw , name='withdraw'),
    url(r'^attended/$', attended_form , name='attended_form'),
    url(r'^attended/search/school$', search_attended , name='search_attended'),
)

urlpatterns += patterns('',
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
#

GENDERS = (
        ('M', 'Male'),
        ('F', 'Female'),
)

YEARLEVELS = (
	  (1, '1'),
	  (2, '2'),
	  (3, '3'),
	  (4, '4'),
	  (5, '5'),
)

TYPE_OF_USER = (
        ('n', 'Normal'),
        ('a', 'Admin'),
)

class NewUser(User):
	usertype = models.CharField(max_length=100, choices=TYPE_OF_USER)

	def __unicode__(self):
		return self.username

class Student(models.Model):
	studentID = models.IntegerField(unique=True)
	lastname = models.CharField(max_length=30)
	firstname = models.CharField(max_length=30)
	gender = models.CharField(max_length = 10, choices=GENDERS)
	school = models.CharField(max_length=60)
	year = models.IntegerField(choices=YEARLEVELS)

	def __unicode__(self):
		return str(self.studentID)

class Event(models.Model):
	name = models.CharField(max_length=50)
	description = models.TextField(null=True,blank=True)
	date_start = models.DateField()

	def __unicode__(self):
		return self.name


class EventList(models.Model):
	account = models.ForeignKey(NewUser)
	event = models.ForeignKey(Event)
	activated = models.BooleanField(default=False)

	def __unicode__(self):
		return str(self.event.name)

profiles/forms.py
from django import forms
from django.forms import ModelForm
from profiles.models import *
from django.contrib.auth.forms import UserCreationForm

class NewUserForm(forms.ModelForm):
    class Meta:
        model = NewUser
        exclude = ('email','first_name','last_name','username','password','is_staff','is_active','is_superuser','last_login','date_joined','user_permissions','groups')

class EventForm(forms.ModelForm):

	class Meta:
		model = Event

class StudentForm(forms.ModelForm):

	class Meta:
		model = Student

profiles/views.py
from django.template import Context
from django.template.loader import get_template
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from profiles import models
from profiles import forms
from django.utils import simplejson
import datetime
from auth.views import admin_required

@admin_required
def create_account(request):
    context = {}
    context['success'] = False
    if request.method == 'POST':
        form1 = forms.UserCreationForm(request.POST)
        form2 = forms.NewUserForm(request.POST)

        if form1.is_valid() and form2.is_valid():
            profile = form2.save(commit=False)
            user = form1.save(commit=False)
            profile.username = user.username
            profile.password = user.password
            profile.save()
            context['success'] = True
            context['user_form'] = forms.NewUserForm()
            context['password_form'] = forms.UserCreationForm()
        else:
            context['password_form'] = form1
            context['user_form'] = form2
    else:
        context['user_form'] = forms.NewUserForm()
        context['password_form'] = forms.UserCreationForm()

    return render_to_response('profiles/create_account.html',context,context_instance=RequestContext(request))

@admin_required
def event(request):
    context = {}
    eventlist = models.EventList.objects.all()
    context['events'] = eventlist

    return render_to_response('profiles/event.html',context,context_instance=RequestContext(request))


@admin_required
def create_event(request):
    context = {}
    context['success'] = False

    if request.method == 'POST':
        form1 = forms.EventForm(request.POST)
        if form1.is_valid():
            f1 = form1.save()
            newuser = models.NewUser.objects.get(id=request.user.id)
            eventlist = models.EventList.objects.create(account=newuser,event=f1,activated=False)
            context['success'] = True
            context['eventform'] = forms.EventForm()
        else:
            context['eventform'] = form1
    else:
        context['eventform'] = forms.EventForm()

    return render_to_response('profiles/create_event.html',context,context_instance=RequestContext(request))

@admin_required
def activate_event(request):
    if request.is_ajax():
        eventid = request.GET.get('q')
        if eventid is not None:
            try:
                activated_event = models.EventList.objects.get(activated=True)
                activated_event.activated = False
                activated_event.save()
            except:
                print 'no events activated'

            newevent = models.EventList.objects.get(pk=eventid)
            newevent.activated = True
            newevent.save()

            request.session['event_activated'] = newevent.event.name
            request.session['event_id'] = newevent.id
            data = simplejson.dumps(newevent.event.name)
            return HttpResponse(data, mimetype='application/javascript')

@admin_required
def deactivate_event(request):
    if request.is_ajax():
        newuser = models.NewUser.objects.get(id=request.user.id)
        eventlist = EventList.objects.get(account=newuser,activated=True)
        eventlist.activated=False
        eventlist.save()

        del request.session['event_activated']
        del request.session['event_id']
        data = simplejson.dumps(eventlist.event.name)
        return HttpResponse(data, mimetype='application/javascript')


@admin_required
def add_student(request):
    context = {}
    context['success'] = False

    if request.method == 'POST':
        form1 = forms.StudentForm(request.POST)
        if form1.is_valid():
            f1 = form1.save()
            context['success'] = True
            context['studentform'] = forms.StudentForm()
        else:
            context['studentform'] = form1
    else:
        context['studentform'] = forms.StudentForm()

    return render_to_response('profiles/add_student.html',context,context_instance=RequestContext(request))

psitsregistration/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.template import Context
from django.template.loader import get_template
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def home(request):
    context = {}

    return render_to_response('index.html', context, RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<link type="text/css" rel="stylesheet" href="/static/css/stylesheet.css">
	<script src="/static/js/jquery-1.9.1.js"></script>

	<title>
        {% block title %}
        {% endblock %}
    </title>

    {% block extracss %}
    {% endblock extracss %}

    {% block extrajstop %}
    {% endblock extrajstop %}

</head>

<body>
	<div class="container">
		{% if request.user.is_authenticated %}
		{% block header %}
		<table class='header-top'>
	        <tr>
	            <td class="right">
	            	{% if request.session.event_id %}
	            		{% if request.session.isadmin %}
	            			<a id="linkoff" href="{% url event %}">{{ request.session.event_activated }}</a> 
	            		{% else %}
	            			<a>{{ request.session.event_activated }}</a> 
	            		{% endif %}
	            		{% else %}
	            		{% if request.session.isadmin %}
	            		<a id="linkoff" href="{% url event %}">None</a>
	            		{% else %}
	            			<a>None</a>
	            		{% endif %}
	            	{% endif %}
	            	(Active Event) |
	            	 {% if request.session.isadmin %}
	                	Logged in as Admin
	                {% else %}
	                	Logged in as Normal User
	                {% endif %}
	            </br>
	                Welcome, {{ request.user.username }}! (<a id="linkoff1" href="{% url logout %}">logout</a>)       
	            </td>
	        </tr>
   		</table>
   		<table class="header-bottom">
	        <tr >
	            <td>
	                <a href="{% url attend %}">Register</a></li>
	            </td>
	            <td>
	            <a href="{% url attended_form %}">Attended</a></li>
	            </td>
	        </tr>
               
</table>
		{% endblock header %}
	{% endif %}
	<div id="content">
		{% block content %}
		{% endblock content %}
	</div>
		<div id="footer">
			{% block footer %}
			<br /><br /><br /><br /><br /><br />
		        <p>Copyright © 2013, <b>Source Code: The Official CSSEC Programming Unit.</b> <p>Ateneo de Davao University</p></b><div class='hint'>All rights reserved.</div></p>
			{% endblock footer %}
		</div>
	</div>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %} PSITS Event Registration {% endblock %}

templates/profiles/add_student.html
{% extends "base.html" %}
{% block title %} Add Student {% endblock %}



{% block content %}
<center><h2>Add New Student</h2></center>
*Note: Add students only if student is not found on the main database(irregulars/other reasons)*
</br>
		{% if success %}
			Student successfully added!
		{% endif %}
		<h3>Please enter student details below</h3>
    <form method="POST">
        {% csrf_token %}
        {{ studentform.as_p }}	

        <right><input type="submit" value="Register" /></right>
	</form>
{% endblock %}

templates/profiles/create_account.html
{% extends "base.html" %}
{% block title %} Create Account {% endblock %}

{% block content %}

		<center><h2>Create New Account</h2></center>
		{% if success %}
			Account successfully created!
		{% endif %}
		<h3>Please enter your details below</h3>
    <form method="POST">
        {% csrf_token %}
        {{ password_form.as_p }}	
        {{ user_form.as_p }}
        
        <right><input type="submit" value="Register" /></right>
	</form>
{% endblock %}

templates/profiles/create_event.html
{% extends "base.html" %}
{% block title %} Create Event {% endblock %}

{% block extracss %}
    <link rel="stylesheet" href="/static/css/ui/themes/smoothness/jquery-ui.css" />
    <style type="text/css">
        .ui-widget { font-family: Lucida Grande, Lucida Sans, Arial, sans-serif; font-size: 0.8em; }
    </style>
{% endblock extracss %}

{% block extrajstop %}
    <script src="/static/js/jquery-1.9.1.js"></script>
    <script src="/static/js/jquery-ui.js"></script>
    <script>
    $(function() {
        $( "#id_date_start" ).datepicker({ dateFormat: 'yy-mm-dd', changeMonth: true, changeYear: true,  showMonthAfterYear: true, showOn: "button", buttonImage: "/static/img/calendar-icon.gif", buttonImageOnly: true, yearRange : 'c-0:c+1'});
    });
    </script>
{% endblock extrajstop %}

{% block content %}
<center><h2>Create New Event</h2></center>
		{% if success %}
			Event successfully created!
		{% endif %}
		<h3>Please enter event details below</h3>
    <form method="POST">
        {% csrf_token %}
        {{ eventform.as_p }}	

        <right><input type="submit" value="Register" /></right>
	</form>
{% endblock %}

templates/profiles/event.html
{% extends "base.html" %}

{% block title %} Events {% endblock %}


{% block extrajstop %}
   <script type="text/javascript">
$( document ).ready( function() {

    $(":radio").click(function() {
    	   q = $(this).val()
                $( 'tr.activate' ).removeClass().addClass('odd')

                $.getJSON( '{% url deactivate_event %}', function(data) {
                     });

                $.getJSON( '{% url activate_event %}?q=' + q, function(data) {
                        $( 'a#linkoff' ).text(data) 
                        $( 'tr#'+ q ).removeClass().addClass('activate') });
            
            });
	});
    </script>
{% endblock extrajstop %}

{% block content %}
</br>
<a href="{% url create_event %}"><input type="submit" id="create_event" value="Create Event" /></a>
<a href="{% url create_account %}"><input type="submit" id="create_account" value="Create Account" /></a>
<a href="{% url add_student %}"><input type="submit" id="create_student" value="Add New Student" /></a>

<h2>Events</h2>
<div id="results">
<div class="margin">
    <table>
    {% if events %}
    <tr class='even'> 
    <td colspan="8" class="right">
	<strong>Found {{ events|length }} event{{ events|pluralize }}</strong>
	</td>
	</tr>
    </table>
    <table>
    <tr>
        <th>Event Name</th>
        <th>Date</th>
        <th>Activated</th>
    </tr>
    {% for e in events %}
        {% if e.activated %}
        <tr class='activate' id ='{{ e.id }}'>
        {% else %}
        <tr class='odd' id ='{{ e.id }}'>
        {% endif %}
            <td>{{ e.event.name }}</td>
            <td>{{ e.event.date_start }}</td>     
            <td>
            {% if e.activated %}
            <input type="radio" name="{{ e.admin.username }}-event" checked="checked" value="{{ e.id }}" id="{{ e.id }}"/>
            {% else %}
            <input type="radio" name="{{ e.admin.username }}-event" value="{{ e.id }}" id="{{ e.id }}" />
            {% endif %}
            </td>
        </tr>
    {% endfor %}
    {% else %}
    <tr class='even'>
    <td>No events created</td>
    </tr>
    {% endif %}
    </tr>
    </table>
</div>
</div>
{% endblock %}